# Generated by Django 2.0 on 2017-12-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jghjgh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gg', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='jh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gg', models.CharField(max_length=4)),
            ],
        ),
    ]
